<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Orchard.Protocol.Tests</AssemblyName>
    <RootNamespace>Orchard.Protocol.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Orchard.Protocol/Orchard.Protocol.csproj" />
  </ItemGroup>
</Project>
