<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Orchard.Mirror.Tests</AssemblyName>
    <RootNamespace>Orchard.Mirror.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Orchard.Mirror.Agent.Windows/Orchard.Mirror.Agent.Windows.csproj" />
    <ProjectReference Include="../../src/Orchard.Mirror.Audio.Windows/Orchard.Mirror.Audio.Windows.csproj" />
    <ProjectReference Include="../../src/Orchard.Mirror.Media/Orchard.Mirror.Media.csproj" />
    <ProjectReference Include="../../src/Orchard.Mirror.Shell/Orchard.Mirror.Shell.csproj" />
    <ProjectReference Include="../../src/Orchard.Mirror.Video.Windows/Orchard.Mirror.Video.Windows.csproj" />
  </ItemGroup>
</Project>
